version: 2
updates:
  - package-ecosystem: npm
    directory: "/"
    schedule:
      interval: daily
      time: "12:00"
      timezone: Europe/Helsinki
    open-pull-requests-limit: 99

  - package-ecosystem: github-actions
    directory: "/"
    schedule:
      interval: daily
      time: "12:00"
      timezone: Europe/Helsinki
