language: node_js
node_js:
- '8'
before_install:
- npm install -g greenkeeper-lockfile@1
before_script:
- greenkeeper-lockfile-update
after_script: greenkeeper-lockfile-upload
env:
  global:
    secure: HvFl2IPa9l5/hn/+ZL/SKvPdCpcLA27GFWCMPJVgqnIY8IIOmI/Xy7RwLglCt9PPnq5ebm62UrmLPkj2N4jbHd2m9HmLUqhHRhjF4B24xFcXifnzrF60+hd1mf31uh0AQICLEuFLcuvc28SogcvAnVAKopyFFDYTmwwbw/J4m6Brefx18OJ6xdQh3BeQQ40wYx8eBdrISP+GkJYOA6Bd6JrzwwYSLgfxR68FQXEsYJv9vKCqBHaREH/IEB7O4nVQiTQbLemj9UJpp1Tr1FETk1YUnPQW6q7SKOZzTRJre4J4tSESemWH8LjoF78P8stimaUIVd5TePFXyRaNxPEsZseq42ChUAdfiEmJuC3vv0GGB4c4f9es9Qlv5DSXO9Yfmphn26fpXaNAUcj6X0+OXHUiCTe1OBoQqo9BsLliwCEjByEiKHlUwEK6PdbhoFD2/Oly7Y+rE4HqJqghd/SBTu8eF0RlLHxURl0hdb9hsjgHI+YRB6WcoaYYzPuegZU0M7xDTrnXWk3ojX2zyr8JKQC70mdW2WuDKkPhGUoSFcSyG2qpklG5foQVrW7XXvYiBA50P1nq1vxMdJ66X1wKcC4bvgT7wo95iXdGtzWqCasg79bSGXsqq4mzy94Y7r2QXmlRqsDIwBmd3ksS2dqU3g7vpOkSbVyxB+spvEcFMRQ=
